apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  TZ: {{ .Values.TZ | default "UTC" | squote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap1
data:
  BEASTHOST: {{ .Values.BEASTHOST | default "readsb" | squote }}
  BEASTPORT: {{ .Values.BEASTPORT | default "30005"  | squote }}
---