apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "planefinder.fullname" . }}
  labels:
    {{- include "planefinder.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "planefinder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "planefinder.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "planefinder.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 30053
              protocol: TCP
            - name: echo
              containerPort: 30054
              protocol: TCP
          env:
            - name: BEASTHOST
              valueFrom:
                configMapKeyRef:
                  key:  BEASTHOST
                  name: {{ .Release.Name }}-configmap1

            - name: BEASTPORT
              valueFrom:
                configMapKeyRef:
                  key:  BEASTPORT
                  name: {{ .Release.Name }}-configmap1

            - name: TZ
              valueFrom:
                configMapKeyRef:
                  key:  TZ
                  name: {{ .Release.Name }}-configmap
            
            - name: SHARECODE
              valueFrom:
                secretKeyRef:
                  key:  SHARECODE
                  name: {{ .Release.Name }}-auth

            - name: LAT
              valueFrom:
                secretKeyRef:
                  key:  LAT
                  name: {{ .Release.Name }}-auth1

            - name: LONG
              valueFrom:
                secretKeyRef:
                  key:  LONG
                  name: {{ .Release.Name }}-auth1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
