apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  SHARECODE: {{ .Values.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth1
data:
  LAT: {{ .Values.password | b64enc }}
  LONG: {{ .Values.password | b64enc }}