# Default values for adsbexchange.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/sdr-enthusiasts/docker-adsbexchange
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "20250127.1736_nohealthcheck"

imagePullSecrets: []
nameOverride: "adsbexchange"
fullnameOverride: "sdr-enthusiasts-adsbexchange"

serviceAccount:
  sa-name:
    enabled: true
    primary: true

service:
  main:
    ports:
      main:
        port: 3142
        protocol: tcp
        targetPort: 3142

autoscaling:
  enabled: false

persistence:
  varrun:
    enabled: true
    type: emptyDir
    mountPath: /var/run
    medium: Memory
    size: 64M
