apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  TZ: {{ .Values.TZ | default "UTC" | squote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap1
data:
  BEASTHOST: {{ .Values.BEASTHOST | default "readsb" | squote }}
  BEASTPORT: {{ .Values.BEASTPORT | default "30005"  | squote }}
  UAT_RECEIVER_HOST: {{ .Values.BEASTHOST | default "readsb" | squote }}
  UAT_RECEIVER_PORT: {{ .Values.BEASTHOST | default "30979" | squote }}
  STATS_INTERVAL_MINUTES: {{ .Values.BEASTHOST | default "5" | squote }}
  VERBOSE_LOGGING: {{ .Values.BEASTHOST | default "false" | squote }}
  DEBUG_LEVEL: {{ .Values.BEASTHOST | default "0" | squote }}
  ENABLE_MLAT: {{ .Values.BEASTHOST | default "true" | squote }}
---