apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  LAT: {{ .Values.password | b64enc }}
  LONG: {{ .Values.password | b64enc }}
  ALT: {{ .Values.password | b64enc }}
  SHARING_KEY: {{ .Values.password | b64enc }}