apiVersion: v1
kind: Service
metadata:
  name: {{ include "adsbexchange.fullname" . }}
  labels:
    {{- include "adsbexchange.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mlat_beast_out
      protocol: TCP
      name: mlat_beast_out
  selector:
    {{- include "adsbexchange.selectorLabels" . | nindent 4 }}
